# Generated by Django 5.1 on 2024-08-21 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('across', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagebanner',
            name='images',
        ),
        migrations.AddField(
            model_name='homepagebanner',
            name='image',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='photo_banner', to='across.photo'),
            preserve_default=False,
        ),
    ]
