# Generated by Django 5.1 on 2024-08-21 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('across', '0002_remove_homepagebanner_images_homepagebanner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoalbum',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='across.category'),
        ),
        migrations.AddField(
            model_name='videoalbum',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='across.category'),
        ),
    ]
